name: Flutter CI

on:
  push:
    branches: [ "examen-parcial-1" ]
  pull_request:
    branches: [ "examen-parcial-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter (Latest Stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test